<?php
/**
 * @file
 * EMBridge module file.
 */

use \Drupal\Core\Link;
use \Drupal\embridge\Entity\EmbridgeAssetEntity;
use \Drupal\embridge\EmbridgeAssetEntityInterface;
use \Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function embridge_theme() {
  return array(
    'embridge_file_link' => [
      'variables' => [
        'asset' => NULL,
        'description' => '',
        'entity' => NULL,
        'link_to' => '',
      ],
    ],
    'embridge_image' => [
      'variables' => [
        'asset' => NULL,
        'conversion' => '',
        'application_id' => '',
        'description' => '',
        'entity' => NULL,
        'link_to' => '',
      ],
    ],
    'embridge_search_results' => [
      'variables' => ['results' => []],
    ],
  );
}

/**
 * Prepares variables for file link templates.
 *
 * Default template: file-link.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - asset: An EMBridge Asset Entity object to which the link will be created.
 *   - entity: The referring entity.
 *   - link_to: whether to link to the content, the file, or nothing.
 *   - description: A description to be displayed instead of the filename.
 *   - attributes: An associative array of attributes to be placed in the a tag.
 */
function template_preprocess_embridge_file_link(&$variables) {
  $asset = $variables['asset'];
  $options = array();

  $asset_entity = ($asset instanceof EmbridgeAssetEntity) ? $asset : EmbridgeAssetEntity::load($asset->id);
  $variables['asset'] = $asset;

  $mime_type = $asset->getMimeType();
  // Set options as per anchor format described at
  // http://microformats.org/wiki/file-format-examples
  $options['attributes']['type'] = $mime_type . '; length=' . $asset->getSize();

  // Use the description as the link text if available.
  if (empty($variables['description'])) {
    $link_text = $asset_entity->getFilename();
  }
  else {
    $link_text = $variables['description'];
    $options['attributes']['title'] = $asset_entity->getFilename();
  }

  $url = NULL;
  if (!empty($variables['entity']) && $variables['link_to'] == 'content') {
    /** @var Drupal\Core\Entity\EntityInterface $entity */
    $entity = $variables['entity'];
    $url = $entity->urlInfo();
  }
  // Add to variables for embridge_image.
  $variables['url'] = $url;

  // Classes to add to the file field for icons.
  $classes = array(
    'file',
    // Add a specific class for each and every mime type.
    'file--mime-' . strtr($mime_type, array('/' => '-', '.' => '-')),
    // Add a more general class for groups of well known mime types.
    'file--' . file_icon_class($mime_type),
  );

  // Set file classes to the options array.
  $variables['attributes'] = new Attribute($variables['attributes']);
  $variables['attributes']->addClass($classes);

  if ($url) {
    $link = Link::fromTextAndUrl($link_text, $url);
  }
  else {
    $link = $link_text;
  }
  $variables['link'] = $link;
}

/**
 * Prepares variables for file link templates.
 *
 * Default template: file-link.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - asset: An EMBridge Asset Entity object to which the link will be created.
 *   - entity: The referring entity.
 *   - link_to: whether to link to the content, the file, or nothing.
 *   - description: A description to be displayed instead of the filename.
 *   - attributes: An associative array of attributes to be placed in the a tag.
 */
function template_preprocess_embridge_image(&$variables) {
  template_preprocess_embridge_file_link($variables);

  $variables['image'] = array(
    '#theme' => 'image',
  );

  /** @var EmbridgeAssetEntity $asset */
  $asset = $variables['asset'];
  $variables['image']['#width'] = $asset->getWidth();
  $variables['image']['#height'] = $asset->getHeight();
  $variables['image']['#alt'] = $variables['description'];

  /** @var \Drupal\embridge\EnterMediaAssetHelperInterface $asset_helper */
  $asset_helper = Drupal::getContainer()->get('embridge.asset_helper');
  $uri = $asset_helper->getAssetConversionUrl($asset, $variables['application_id'], $variables['conversion']);
  if ($variables['link_to'] == 'file') {
    $variables['url'] = $uri;
  }

  $variables['image']['#uri'] = $uri;
}

/**
 * Checks that a file meets the criteria specified by the validators.
 *
 * After executing the validator callbacks specified hook_file_validate() will
 * also be called to allow other modules to report errors about the file.
 *
 * @param EmbridgeAssetEntityInterface $asset
 *   A file entity.
 * @param array $validators
 *   An optional, associative array of callback functions used to validate the
 *   file. The keys are function names and the values arrays of callback
 *   parameters which will be passed in after the file entity. The
 *   functions should return an array of error messages; an empty array
 *   indicates that the file passed validation. The functions will be called in
 *   the order specified.
 *
 * @return array
 *   An array containing validation error messages.
 *
 * @deprecated
 *   Use EmbridgeAssetValidator::validate(),
 */
function embridge_asset_validate(EmbridgeAssetEntityInterface $asset, $validators = array()) {
  /** @var \Drupal\embridge\EmbridgeAssetValidator $validator */
  $validator = \Drupal::getContainer()->get('embridge.asset_validator');

  return $validator->validate($asset, $validators);
}