embridge.embridge_catalog.*:
  type: config_entity
  label: 'EMBridge Catalog config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    applicationId:
      type: string
      label: 'Application ID'
    conversions:
      type: string
      label: 'Conversions'
    uuid:
      type: string
